### ISSUE TITLE
Little information in the ReadMe

### ISSUE THREAD

**Issue by danon** [madebybob/php-number#6]
You said in your ReadMe.md that the library could be used for weights, currencies and other values, yet in the examples you only show simple integer operations and basic add/subtract.

Perhaps it be more beneficial to skip the simple arithmetics and put more complex examples? LIke with currency or weights.

**Comment by bobmulder** [comment]
Hi there @Danon,

thanks for your issue. I understand your suggestion.

The scope of this package is not to support numeral types like weights and currencies, but to make handling numbers (like them) easier and prettier in PHP. 

I have updated the readme to point that out.

Furthermore, I understand that in your case you need to work with weights and currencies. As the readme suggests, we encourage you to create your own implementations of the `AbstractNumber` class. I agree with you this should be explained much better. Therefor I have created an example repository here: https://github.com/madebybob/php-number-examples. The code is up to date, some docs need to be done. So hang on for that 👍 

Thank you again, I hope this will help you!

Bob
